'use client';

import React, { useState, useRef } from 'react';
import Link from 'next/link';
import { useAppStore } from '@/lib/store';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import Icon from '@/components/ui/AppIcon';

interface DeepDiveReport {
    companyName: string;
    sector: string;
    date: string;
    verdict: string;
    verdictReason: string;
    executiveSummary: string;
    thesis: string;
    financialAnalysis: string;
    valuationAssessment: string;
    ipoOutlook: string;
    riskFactors: string[];
    catalysts: string[];
    newsDigest: string;
    priceTarget: string;
    keyMetrics: {
        revenue: string;
        pat: string;
        revenueGrowth: string;
        ipoLikelihood: string;
        riskRating: string;
    };
}

export default function DeepDivePage() {
    const { companies } = useAppStore();
    const [selectedCompanyId, setSelectedCompanyId] = useState<string>('');
    const [report, setReport] = useState<DeepDiveReport | null>(null);
    const [loading, setLoading] = useState(false);
    const [cached, setCached] = useState(false);
    const [generatedAt, setGeneratedAt] = useState<string | null>(null);
    const reportRef = useRef<HTMLDivElement>(null);

    const generateReport = async (forceRefresh = false) => {
        if (!selectedCompanyId) return;
        setLoading(true);
        setReport(null);
        try {
            const res = await fetch('/api/ai/deep-dive', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ companyId: selectedCompanyId, forceRefresh }),
            });
            const data = await res.json();
            if (data.report) {
                setReport(data.report);
                setCached(data.cached);
                setGeneratedAt(data.generatedAt);
            }
        } catch {
            // error handled silently
        } finally {
            setLoading(false);
        }
    };

    const exportPDF = async () => {
        if (!report) return;
        const { default: jsPDF } = await import('jspdf');
        const doc = new jsPDF();
        const margin = 20;
        let y = 20;

        const addText = (text: string, fontSize: number, bold = false, maxWidth = 170) => {
            doc.setFontSize(fontSize);
            doc.setFont('helvetica', bold ? 'bold' : 'normal');
            const lines = doc.splitTextToSize(text, maxWidth);
            lines.forEach((line: string) => {
                if (y > 275) { doc.addPage(); y = 20; }
                doc.text(line, margin, y);
                y += fontSize * 0.5;
            });
            y += 3;
        };

        addText(`${report.companyName} — Investment Memo`, 18, true);
        addText(`${report.sector} | ${report.date} | Verdict: ${report.verdict}`, 10, false);
        y += 5;

        addText('Executive Summary', 13, true);
        addText(report.executiveSummary, 10);
        y += 3;

        addText('Investment Thesis', 13, true);
        addText(report.thesis, 10);
        y += 3;

        addText('Financial Analysis', 13, true);
        addText(report.financialAnalysis, 10);
        y += 3;

        addText('Valuation Assessment', 13, true);
        addText(report.valuationAssessment, 10);
        addText(`12-Month Price Target: ${report.priceTarget}`, 10, true);
        y += 3;

        addText('IPO Outlook', 13, true);
        addText(report.ipoOutlook, 10);
        y += 3;

        addText('Risk Factors', 13, true);
        report.riskFactors.forEach((r, i) => addText(`${i + 1}. ${r}`, 10));
        y += 3;

        addText('Catalysts', 13, true);
        report.catalysts.forEach((c, i) => addText(`${i + 1}. ${c}`, 10));
        y += 5;

        doc.setFontSize(8);
        doc.setTextColor(150);
        doc.text('Generated by ShareSaathi AI — For informational purposes only', margin, 290);

        doc.save(`${report.companyName.replace(/\s+/g, '_')}_Deep_Dive.pdf`);
    };

    const verdictColor = report?.verdict === 'BUY' ? 'bg-green-100 text-green-700 border-green-300' : report?.verdict === 'AVOID' ? 'bg-red-100 text-red-700 border-red-300' : 'bg-amber-100 text-amber-700 border-amber-300';

    return (
        <div className="container mx-auto px-4 md:px-8 py-8 max-w-5xl">
            <div className="flex items-center gap-2 mb-1">
                <Link href="/dashboard/customer" className="text-muted hover:text-foreground transition-colors">
                    <Icon name="ArrowLeftIcon" size={18} />
                </Link>
                <h1 className="text-3xl font-display font-light tracking-tight text-foreground">Company Deep Dive</h1>
            </div>
            <p className="text-muted mt-1 mb-8">AI-generated investment research memo with financial analysis, IPO outlook, and risk assessment.</p>

            {/* Company Selector */}
            <Card className="border-border shadow-sm mb-8">
                <CardContent className="p-6">
                    <div className="flex flex-col sm:flex-row gap-4">
                        <select
                            value={selectedCompanyId}
                            onChange={(e) => { setSelectedCompanyId(e.target.value); setReport(null); }}
                            className="flex-1 bg-surface border border-border rounded-lg px-4 py-3 text-sm text-foreground focus:outline-none focus:border-primary transition-colors"
                        >
                            <option value="">Select a company...</option>
                            {companies.map(c => (
                                <option key={c.id} value={c.id}>{c.name} — {c.sector}</option>
                            ))}
                        </select>
                        <Button
                            onClick={() => generateReport(false)}
                            disabled={!selectedCompanyId || loading}
                            className="bg-primary text-white hover:bg-primary/90 px-8"
                        >
                            {loading ? (
                                <span className="flex items-center gap-2">
                                    <div className="h-4 w-4 border-2 border-white border-t-transparent rounded-full animate-spin" />
                                    Generating...
                                </span>
                            ) : 'Generate Report'}
                        </Button>
                    </div>
                </CardContent>
            </Card>

            {/* Report */}
            {report && (
                <div ref={reportRef} className="space-y-6">
                    {/* Report Header */}
                    <Card className="border-border shadow-sm overflow-hidden">
                        <div className="bg-gradient-to-r from-blue-50 to-indigo-50 p-6">
                            <div className="flex items-start justify-between mb-4">
                                <div>
                                    <h2 className="text-2xl font-bold text-foreground">{report.companyName}</h2>
                                    <p className="text-sm text-muted mt-1">{report.sector} · {report.date}</p>
                                </div>
                                <div className={`px-4 py-2 rounded-lg border-2 font-bold text-lg ${verdictColor}`}>
                                    {report.verdict}
                                </div>
                            </div>
                            <p className="text-sm text-foreground/80 italic">{report.verdictReason}</p>

                            {/* Key Metrics Bar */}
                            <div className="grid grid-cols-2 sm:grid-cols-5 gap-3 mt-5">
                                {[
                                    { label: 'Revenue', value: report.keyMetrics.revenue },
                                    { label: 'PAT', value: report.keyMetrics.pat },
                                    { label: 'Rev Growth', value: report.keyMetrics.revenueGrowth },
                                    { label: 'IPO Likelihood', value: report.keyMetrics.ipoLikelihood },
                                    { label: 'Risk', value: report.keyMetrics.riskRating },
                                ].map(m => (
                                    <div key={m.label} className="bg-white/80 rounded-lg p-3 border border-border/50">
                                        <p className="text-[10px] uppercase tracking-widest text-muted font-bold">{m.label}</p>
                                        <p className="text-sm font-bold text-foreground mt-1">{m.value}</p>
                                    </div>
                                ))}
                            </div>
                        </div>
                    </Card>

                    {/* Executive Summary */}
                    <Card className="border-border shadow-sm">
                        <CardHeader className="border-b border-border/50 pb-3">
                            <CardTitle className="font-display font-medium text-lg flex items-center gap-2">
                                <Icon name="DocumentTextIcon" size={18} className="text-blue-600" />
                                Executive Summary
                            </CardTitle>
                        </CardHeader>
                        <CardContent className="p-5">
                            <p className="text-sm text-foreground leading-relaxed">{report.executiveSummary}</p>
                        </CardContent>
                    </Card>

                    {/* Investment Thesis */}
                    <Card className="border-border shadow-sm">
                        <CardHeader className="border-b border-border/50 pb-3">
                            <CardTitle className="font-display font-medium text-lg flex items-center gap-2">
                                <Icon name="LightBulbIcon" size={18} className="text-amber-600" />
                                Investment Thesis
                            </CardTitle>
                        </CardHeader>
                        <CardContent className="p-5">
                            <p className="text-sm text-foreground leading-relaxed whitespace-pre-line">{report.thesis}</p>
                        </CardContent>
                    </Card>

                    {/* Financial Analysis */}
                    <Card className="border-border shadow-sm">
                        <CardHeader className="border-b border-border/50 pb-3">
                            <CardTitle className="font-display font-medium text-lg flex items-center gap-2">
                                <Icon name="ChartBarIcon" size={18} className="text-green-600" />
                                Financial Analysis
                            </CardTitle>
                        </CardHeader>
                        <CardContent className="p-5">
                            <p className="text-sm text-foreground leading-relaxed whitespace-pre-line">{report.financialAnalysis}</p>
                        </CardContent>
                    </Card>

                    {/* Valuation + Price Target */}
                    <Card className="border-border shadow-sm">
                        <CardHeader className="border-b border-border/50 pb-3">
                            <CardTitle className="font-display font-medium text-lg flex items-center gap-2">
                                <Icon name="CurrencyRupeeIcon" size={18} className="text-purple-600" />
                                Valuation Assessment
                            </CardTitle>
                        </CardHeader>
                        <CardContent className="p-5">
                            <p className="text-sm text-foreground leading-relaxed whitespace-pre-line mb-4">{report.valuationAssessment}</p>
                            <div className="inline-flex items-center gap-2 bg-purple-50 border border-purple-200 rounded-lg px-4 py-2">
                                <Icon name="ArrowTrendingUpIcon" size={16} className="text-purple-600" />
                                <span className="text-sm font-bold text-purple-800">12M Target: {report.priceTarget}</span>
                            </div>
                        </CardContent>
                    </Card>

                    {/* IPO Outlook */}
                    <Card className="border-border shadow-sm">
                        <CardHeader className="border-b border-border/50 pb-3">
                            <CardTitle className="font-display font-medium text-lg flex items-center gap-2">
                                <Icon name="RocketLaunchIcon" size={18} className="text-orange-600" />
                                IPO Outlook
                            </CardTitle>
                        </CardHeader>
                        <CardContent className="p-5">
                            <p className="text-sm text-foreground leading-relaxed whitespace-pre-line">{report.ipoOutlook}</p>
                        </CardContent>
                    </Card>

                    {/* Risk Factors + Catalysts side by side */}
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                        <Card className="border-border shadow-sm">
                            <CardHeader className="border-b border-border/50 pb-3">
                                <CardTitle className="font-display font-medium text-lg flex items-center gap-2">
                                    <Icon name="ExclamationTriangleIcon" size={18} className="text-red-600" />
                                    Risk Factors
                                </CardTitle>
                            </CardHeader>
                            <CardContent className="p-4 space-y-2">
                                {report.riskFactors.map((risk, i) => (
                                    <div key={i} className="flex items-start gap-2 p-2 rounded-lg bg-red-50/50">
                                        <span className="w-5 h-5 rounded-full bg-red-100 text-red-600 flex items-center justify-center text-xs font-bold shrink-0">{i + 1}</span>
                                        <p className="text-xs text-foreground">{risk}</p>
                                    </div>
                                ))}
                            </CardContent>
                        </Card>

                        <Card className="border-border shadow-sm">
                            <CardHeader className="border-b border-border/50 pb-3">
                                <CardTitle className="font-display font-medium text-lg flex items-center gap-2">
                                    <Icon name="BoltIcon" size={18} className="text-green-600" />
                                    Catalysts
                                </CardTitle>
                            </CardHeader>
                            <CardContent className="p-4 space-y-2">
                                {report.catalysts.map((cat, i) => (
                                    <div key={i} className="flex items-start gap-2 p-2 rounded-lg bg-green-50/50">
                                        <span className="w-5 h-5 rounded-full bg-green-100 text-green-600 flex items-center justify-center text-xs font-bold shrink-0">{i + 1}</span>
                                        <p className="text-xs text-foreground">{cat}</p>
                                    </div>
                                ))}
                            </CardContent>
                        </Card>
                    </div>

                    {/* News Digest */}
                    {report.newsDigest && (
                        <Card className="border-border shadow-sm">
                            <CardHeader className="border-b border-border/50 pb-3">
                                <CardTitle className="font-display font-medium text-lg flex items-center gap-2">
                                    <Icon name="NewspaperIcon" size={18} className="text-blue-600" />
                                    Recent News Digest
                                </CardTitle>
                            </CardHeader>
                            <CardContent className="p-5">
                                <p className="text-sm text-foreground leading-relaxed">{report.newsDigest}</p>
                            </CardContent>
                        </Card>
                    )}

                    {/* Actions */}
                    <div className="flex flex-wrap items-center gap-3">
                        <Button onClick={exportPDF} className="bg-primary text-white hover:bg-primary/90">
                            <Icon name="ArrowDownTrayIcon" size={16} className="mr-2" />
                            Export PDF
                        </Button>
                        <Button variant="outline" onClick={() => generateReport(true)}>
                            <Icon name="ArrowPathIcon" size={16} className="mr-2" />
                            Regenerate
                        </Button>
                        {cached && generatedAt && (
                            <span className="text-xs text-muted">
                                Cached report from {new Date(generatedAt).toLocaleDateString('en-IN', { day: 'numeric', month: 'short', hour: '2-digit', minute: '2-digit' })}
                            </span>
                        )}
                    </div>
                </div>
            )}

            {/* Empty state */}
            {!report && !loading && (
                <div className="py-16 text-center">
                    <Icon name="DocumentMagnifyingGlassIcon" size={40} className="mx-auto text-muted mb-4" />
                    <p className="text-muted font-medium mb-2">Select a company to generate a deep dive report.</p>
                    <p className="text-xs text-muted">AI will analyze financials, news, IPO outlook, and more.</p>
                </div>
            )}
        </div>
    );
}
