-- 1. Add 'agent' to user_role ENUM (wrapped in DO block for safety if it already exists)
DO $$ BEGIN
    CREATE TYPE user_role_new AS ENUM ('admin', 'staffmanager', 'rm', 'customer', 'agent');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;
-- Assuming PostgreSQL 12+, ALTER TYPE ADD VALUE IF NOT EXISTS is cleaner:
ALTER TYPE user_role ADD VALUE IF NOT EXISTS 'agent';


-- 2. AGENT PROFILES TABLE (Extends profiles)
CREATE TABLE IF NOT EXISTS agent_profiles (
    agent_id UUID PRIMARY KEY REFERENCES profiles(id) ON DELETE CASCADE,
    pan_number TEXT,
    aadhar_number TEXT,
    bank_details JSONB DEFAULT '{}'::jsonb, -- e.g., {"account_name": "", "account_number": "", "ifsc": ""}
    kyc_status TEXT DEFAULT 'pending', -- 'pending', 'approved', 'rejected'
    total_earnings NUMERIC DEFAULT 0,
    withdrawn_earnings NUMERIC DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. AGENT SETTINGS TABLE (Granular Config)
CREATE TABLE IF NOT EXISTS agent_settings (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    -- Can be global (agent_id IS NULL, company_id IS NULL)
    -- specific to a company (agent_id IS NULL)
    -- specific to an agent (company_id IS NULL)
    -- specific to an agent + company combo.
    agent_id UUID REFERENCES agent_profiles(agent_id) ON DELETE CASCADE,
    company_id UUID REFERENCES companies(id) ON DELETE CASCADE,
    fixed_markup NUMERIC DEFAULT 5,         -- Platform's fixed cut per share
    margin_threshold NUMERIC DEFAULT 10,    -- Min margin difference before profit sharing activates
    margin_percentage NUMERIC DEFAULT 20,   -- Platform percentage cut when margin > threshold
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE NULLS NOT DISTINCT (agent_id, company_id)
);

-- Seed a default global setting (agent_id = NULL, company_id = NULL) if empty
INSERT INTO agent_settings (agent_id, company_id, fixed_markup, margin_threshold, margin_percentage)
SELECT NULL, NULL, 5, 10, 20
WHERE NOT EXISTS (SELECT 1 FROM agent_settings WHERE agent_id IS NULL AND company_id IS NULL);

-- 4. AGENT CLIENT ORDERS (The custom links generated by agents)
CREATE TABLE IF NOT EXISTS agent_client_orders (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    agent_id UUID REFERENCES agent_profiles(agent_id) ON DELETE CASCADE,
    company_id UUID REFERENCES companies(id) ON DELETE CASCADE,
    client_name TEXT NOT NULL,
    client_email TEXT NOT NULL,
    client_phone TEXT,
    quantity INTEGER NOT NULL,
    base_price NUMERIC NOT NULL,     -- The platform price at the time of creation
    fixed_markup NUMERIC NOT NULL,   -- The fixed markup at the time of creation
    selling_price NUMERIC NOT NULL,  -- Agent's Custom Price
    status TEXT DEFAULT 'pending',   -- 'pending', 'paid', 'cancelled'
    link_token TEXT UNIQUE NOT NULL DEFAULT encode(gen_random_bytes(16), 'hex'),
    -- Post payment values
    platform_cut NUMERIC DEFAULT 0,
    agent_earnings NUMERIC DEFAULT 0,
    razorpay_order_id TEXT,
    razorpay_payment_id TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- TRIGGERS
DO $$ BEGIN
    CREATE TRIGGER update_agent_profiles_modtime BEFORE UPDATE ON agent_profiles FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
    CREATE TRIGGER update_agent_settings_modtime BEFORE UPDATE ON agent_settings FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
    CREATE TRIGGER update_agent_client_orders_modtime BEFORE UPDATE ON agent_client_orders FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- RLS
ALTER TABLE agent_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE agent_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE agent_client_orders ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if running multiple times (optional, but good for idempotency)
DROP POLICY IF EXISTS "Agents can view own profile" ON agent_profiles;
DROP POLICY IF EXISTS "Agents can update own profile" ON agent_profiles;
DROP POLICY IF EXISTS "Agents can insert own profile" ON agent_profiles;
DROP POLICY IF EXISTS "Admins can manage agent profiles" ON agent_profiles;
DROP POLICY IF EXISTS "Admins can view agent profiles" ON agent_profiles;

DROP POLICY IF EXISTS "Anyone can view agent settings" ON agent_settings;
DROP POLICY IF EXISTS "Admins can manage agent settings" ON agent_settings;

DROP POLICY IF EXISTS "Agents can manage own orders" ON agent_client_orders;
DROP POLICY IF EXISTS "Anyone can view order by link_token" ON agent_client_orders;
DROP POLICY IF EXISTS "Admins can view all agent orders" ON agent_client_orders;

-- Agent Profiles Policies
CREATE POLICY "Agents can view own profile" ON agent_profiles FOR SELECT USING (auth.uid() = agent_id);
CREATE POLICY "Agents can update own profile" ON agent_profiles FOR UPDATE USING (auth.uid() = agent_id);
CREATE POLICY "Agents can insert own profile" ON agent_profiles FOR INSERT WITH CHECK (auth.uid() = agent_id);
CREATE POLICY "Admins can manage agent profiles" ON agent_profiles FOR ALL USING (
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
);

-- Agent Settings Policies
CREATE POLICY "Anyone can view agent settings" ON agent_settings FOR SELECT USING (true);
CREATE POLICY "Admins can manage agent settings" ON agent_settings FOR ALL USING (
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
);

-- Agent Client Orders Policies
CREATE POLICY "Agents can manage own orders" ON agent_client_orders FOR ALL USING (auth.uid() = agent_id);
-- Allow public viewing if link_token is matched (necessary for checkout page)
-- Without auth.uid(), this is for anonymous users visiting the checkout link. 
CREATE POLICY "Anyone can view order" ON agent_client_orders FOR SELECT USING (true); 
CREATE POLICY "Admins can view all agent orders" ON agent_client_orders FOR SELECT USING (
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
);
CREATE POLICY "Admins can update all agent orders" ON agent_client_orders FOR UPDATE USING (
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
);
